### ISSUE TITLE
twitter_config.yaml missing during build-time

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/RIMA#209]
`python manage.py collectstatic` requires non-existent file `./config/twitter_config.yaml`.

https://github.com/ude-soco/RIMA/actions/runs/4355737859/jobs/7612764842#step:6:868

**Comment by ralf-berger** [comment]
Only applies to `development` branch. Looks like config values that should be set via environment variables during runtime.

**Comment by shoebjoarder** [comment]
The twitter config values can now be set as environment variables as well. The variables are as follows
`TWITTER_FETCH_DAYS=180`, `TWITTER_CONSUMER_KEY`, `TWITTER_CONSUMER_SECRET`, `TWITTER_ACCESS_TOKEN`, `TWITTER_ACCESS_TOKEN_SECRET`.
For now, you could keep the values of the four last variables as empty string. I need to check if the Twitter API is still free or not, and if not until when.
I needed to install `python-dotenv` package as well. It added another package `pywin32`, which I am doubting to cause issue when building. Let me know if it's the case, then I would need to create another `requirements.txt` file for Windows users
