### ISSUE TITLE
Fork "development": BASE_URL missing

### ISSUE THREAD

**Issue by shoebjoarder** [ude-soco/RIMA#328]
Problem while signing up in the application using the UI. Currently, the requested URL is `https://development.rima.soco.inko.cloud/auth/undefined/api/accounts/register/` for the registration button. I believe it should be `https://development.rima.soco.inko.cloud/api/accounts/register/`.

**Comment by ralf-berger** [comment]
Marking as a valid request, affecting RIMA-Frontend

**Comment by ralf-berger** [comment]
RIMA-Frontend startup log looks good: `Rewriting http://127.0.0.1:8000 to https://development.rima.soco.inko.cloud ...`

**Comment by ralf-berger** [comment]
Testing locally, clicking „SIGN IN” results in Browser console output: `Warning: The tag <medium> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.`

**Comment by ralf-berger** [comment]
An undefined `BASE_URL` would likely cause the observable behavior. In a4e62df the `BASE_URL` value was replaced by an environment variable, but neither set during build nor defaults provided.

**Comment by ralf-berger** [comment]
`BASE_URL_CONFERENCE` is also required, but missing from `example.env`. Need to set default. Judging from [various URLs that don't actually rely on said variable](https://github.com/ude-soco/RIMA/blob/c6102719b448689eda61733b60e62766498fbe88/RIMA-Frontend/nodejs/src/Services/api.js#L157), `BASE_URL + "/api/conferences"` might be the correct value.

[edit:] Those derived constants actually seem to require a trailing slash.

**Comment by ralf-berger** [comment]
Fixed via c610271, 19f70ab. Deployed RIMA-Frontend now sends requests to e. g. `https://development.rima.soco.inko.cloud/api/accounts/login/` or `https://development.rima.soco.inko.cloud/api/accounts/register/`, each yielding an `HTTP 405`.
