### ISSUE TITLE
Fork "development": Database abstraction layer error

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/RIMA#330]
When trying to log in, RIMA-Backend fails with:

```
File "/home/app/.venv/lib/python3.7/site-packages/django/db/backends/postgresql/utils.py", ⏎
    line 6, in utc_tzinfo_factory
  raise AssertionError("database connection isn't set to UTC")
```

**Comment by ralf-berger** [comment]
psycopg2 doesn't work with very outdated/unsupported Django version: https://github.com/psycopg/psycopg2/issues/1293

**Comment by ralf-berger** [comment]
Stuck trying to pin psycopg2 to lower version number:

```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. ⏎
    You likely have a mismatch in your sub-dependencies.
```

**Comment by ralf-berger** [comment]
Trying out Poetry to determine version mismatches after learning that Pipenv doesn't really support dependency resolution.

**Comment by ralf-berger** [comment]
@shoebjoarder Please downgrade psycopg2 to `~=2.8.6`.

**Comment by shoebjoarder** [comment]
In [4d0e6cc](https://github.com/ude-soco/RIMA/commit/4d0e6cc0a5e36c601d48f7fd706c587f73af8143) psycopg2 has been downgraded to 2.8.6 in Pipfile.
