### ISSUE TITLE
Backend Deployment Issues List

### ISSUE THREAD

**Issue by Mouadh-Guesmi** [ude-soco/RIMA#5]
- Install/run application as a non-root user (done for the frontend, **not yet for the backend**)
- Create Dockerfile (multi-stage: build React app, add built assets to the web-server image)
- Make application setting configurable via environment variables at runtime (esp. the base path that is used to build remote URLs)
- Check for other hidden dependencies or hard-coded configurations
- Optimize Dockerfile by:
     - concatenating commands
     - utilizing multi-stage builds 
     - running a small base image
     - checking command order

- Remove model files from image build, put them on e.g. public cloud storage, and fetch them on startup

- move build step (collectstatic) from start.sh into Dockerfile _(low priority)_

**Comment by ralf-berger** [comment]
* resolved 1, 2, 5.1, 5.3, 5.4, 7
* created actionable tickets for the rest
